### ISSUE TITLE
Enhance validation rules for OP1 schemas

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#108]
The following changes need to be made to the validation rules:

[See validation spreadsheet for details](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr) Spec Updates Sheet for yellow highlights in the Notes column. There are comments for each.

**6 OP1 Transactions**
Individual
Tribal
JF Transfer
PAC JF Transfer Memo
Offsets to Opex
Other Receipts

HDR Record

**4 Contact Type Specs**
Individual - good, no changes
Candidate - good, no changes
Committee - good, no changes
Organization - Out of place rule reference for Type

Form 3X (non-agg fields)

Should we list out all possible report codes here (col seq 10)? Answer: TBD

## QA Notes ##
The transaction type and create F3X forms should still work as expected with the appropriate validation error messages appearing in red below the input fields when values break the validation rules.

This will be tested in Code Review. QA.   DEV to provide smoke testing on this ticket as back end, not QA testable.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA

**Comment by WiseQA** [comment]
QA Visual Inspection on this ticket passes QA review.

QA  Review Completed.  Moved to Stage Ready.
