### ISSUE TITLE
Create diff script for JSON schema and spec spreadsheets

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#161]
Create a new python script that reads in the spec from the spec spreadsheet and compares it to the corresponding schema JSON file to find differences that should be corrected.

[Spec spreadsheets](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1216228558)

**DEV NOTES**
Methods for reading in the spreadsheet and JSON files can be gleaned from other scripts in the /bin directory of the validate repo

**ACCEPTANCE CRITERIA**
An output report with differences listed between the spec spreadsheets and the schema JSON files.

**QA NOTES**
QA will consist of a visual inspection of the output reports.
spec_verification_report.txt

**Comment by Elaine-Krauss-TCG** [comment]
The tool is still a work in progress, but it has already caught one (extremely minor, non-functional) error:

In the Individual Receipt Non-Contribution Account JSON Schema, the contribution purpose description is not in the list of required fields.  This does not affect functionality because it still won't accept any value other than "Non-contribution Account Receipt"

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/dfa5e3a1-9681-48d5-b6af-9f6b6b21bf15)

**Comment by Elaine-Krauss-TCG** [comment]
Script Feature-set

- [x] Type Comparison (I.E. "A/N-8")
- [x] Check Required (In the list, conditionally required, and "X (error)"
- [x] Sample Data Comparison
- [x] Check Form Type
- [x] Check Entity Type
- [x] Check Aggregation Group
- [ ] Optionally specify the excel file as an argument
- [ ] Automatically download latest version of the spec sheet (Maybe possible?)

**Comment by Elaine-Krauss-TCG** [comment]
The script first lists out any spec sheets where it could not find a corresponding json file and then any spec sheets where it could not find a Transaction Type Identifier

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/1f3ccedf-c185-4fa8-ac1a-30ebaeb5baaa)

**Comment by Elaine-Krauss-TCG** [comment]
Then it lists out any transactions where errors were found in alphabetical order.

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/4e872585-b4d8-4d09-8a59-55224342d169)

**Comment by mjtravers** [comment]
Returning to In Progress. Some changes requested from CR.

**Comment by WiseQA** [comment]
@mjtravers @AureliaKhorsand what format are these spec spreadsheets output reports in for a visual inspection as denoted in QA Review ?

**Comment by AureliaKhorsand** [comment]
@mjtravers @Elaine-Krauss-TCG can one of you send @WiseQA the report (.txt file)? Shelly - it will be a text file that lists transactions under each error that is found. We can hop on a call if you have more questions. Thanks!

**Comment by Elaine-Krauss-TCG** [comment]
[spec_verification_report.txt](https://app.zenhub.com/files/184271254/d59e8087-9b3e-4f63-a1a5-bf2d6af6cd41/download)

**Comment by Elaine-Krauss-TCG** [comment]
@WiseQA An example report is included above

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review is a visual inspection of this report as BA's will verify content is correct.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/084958e6-2da2-4abd-b0ab-f616118de12c)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/459be71a-2095-4b38-88fb-2d04be2e6483)

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/7c03530c-a5bc-49ea-885d-05ac025f51a3)

[https://app.zenhub.com/files/184271254/7f8acc3a-0059-4284-93be-f96d04202e2d/download](https://app.zenhub.com/files/184271254/7f8acc3a-0059-4284-93be-f96d04202e2d/download)
