### ISSUE TITLE
Create diff script for JSON schema and spec spreadsheets - CONSOLIDATED specs

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-validate#175]
Update/create new python script that reads in the spec from the spec spreadsheet and compares it to the corresponding schema JSON file to find differences that should be corrected. **This script should be able to address consolidated specifications.**

DEV NOTES
Methods for reading in the spreadsheet and JSON files can be gleaned from other scripts in the /bin directory of the validate repo

ACCEPTANCE CRITERIA
An output report with differences listed between the spec spreadsheets and the schema JSON files.

QA NOTES
QA will consist of a visual inspection of the output reports.
spec_verification_report.txt

**Comment by Elaine-Krauss-TCG** [comment]
Consolidated specs are now being tested, and a few small errors have been found
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/5e175ce7-e9bb-43ab-b9cc-6446980e793a)

**Comment by Elaine-Krauss-TCG** [comment]
[A copy of the spec verification report](https://app.zenhub.com/files/184271254/38a8c611-a91d-468b-b55d-b9e86c3d5c7a/download)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review cannot be completed.   This is up to BA's to verify output of this ticket.   Moving to stage ready without QA review.
