### ISSUE TITLE
Add Schedule C to Data Dictionary

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#180]
In order to get the validation working with the back and front ends, a JSON validation spec needs to be created and linked into the online data dictionary as a baseline spec for the Schedule C transaction type definition specifications.

You can find the Schedule C specification from the Vendor pack: [HERE](https://docs.google.com/spreadsheets/d/18TtYCHWjj0gbsubJXQTbALEkbK_t93t0/edit#gid=1726907415)

**Tasks:**

- Create a JSON validation file for the Schedule C
- Put the JSON validation file created for Schedule C and put it in the schema directory of the GitHub repo along with the other schema JSON files
- Name the Schedule C JSON file in the schema directory in the GitHub repository "SchC.json"
- Create the online documentation in the repository docs directory by running the bin/generate-schema-docs.sh script
- Update the docs/index.html page to include the new Schedule C schema in the [Forms & Schedules](https://fecgov.github.io/fecfile-validate/) section of the index.html page

**Comment by mjtravers** [comment]
Create a Schedule C JSON spec file and spec files for the

**Comment by toddlees** [comment]
Schedule C is now available on the [data dictionary](https://fecgov.github.io/fecfile-validate/):
[json](https://github.com/fecgov/fecfile-validate/blob/develop/schema/SchC.json)
[doc](https://fecgov.github.io/fecfile-validate/SchC.html)
[spec](https://fecgov.github.io/fecfile-validate/SchC_spec.html)
![image.png](https://images.zenhubusercontent.com/61d5a806b7deecb063ca11f9/4765a81d-f8ba-476c-a6a5-99eb95ef63bd)
