### ISSUE TITLE
Run spec diff script for Schedule B JSON files

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#181]
When the Schedule B transaction tickets are complete, run the spec diff script to find any discrepancies between the spreadsheets and the JSON files. Proceed to make corrections so that the diff script runs without reporting any errors.

### QA Notes:

Changes were made to 11 different schema files.  The ones that have had functionality changes are as follows:

SchB:
 - NON_CONTRIBUTION_ACCOUNT_DISBURSEMENT
   - Aggregate Amount added to validation schema
 - NON_CONTRIBUTION_ACCOUNT_STAFF_REIMBURSEMENT
   - Aggregate Amount added to validation schema
 - NON_CONTRIBUTION_MEMOS
   - Aggregate Amount added to validation schema
 - NON_CONTRIBUTION_PARENTS
   - Aggregate Amount added to validation schema

SchA:
 - INDIVIDUAL_NATIONAL_PARTY_CONVENTION_JF_TRANSFER_MEMO
   - Employer/Occupation was always required; now it is conditionally required
 - PARTNERSHIP_INDIVIDUAL_NATIONAL_PARTY_HEADQUARTERS_JF_TRANSFER_MEMO
   - The contribution purpose description's pattern accepted values 103 characters long

**Comment by Elaine-Krauss-TCG** [comment]
After making a few changes to get the script to run with Schedule B, here is the first error report:
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/4f5d24ba-907c-41fe-83de-cd822b3df644)
The full report can be downloaded [here](https://app.zenhub.com/files/184271254/8151e832-15b7-4bab-92d0-9d3b09dc8b5c/download)

**Comment by Elaine-Krauss-TCG** [comment]
Most of these errors are false positives and/or the result of stylistic changes in the excel sheets.  These will have to be addressed before true divergences can be identified

**Comment by Elaine-Krauss-TCG** [comment]
After meeting with Aurelia and Gregg, the last of the discrepancies have been resolved and we're at 0 errors in Schedule B

![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0207f3c3-5d8f-4a9f-ac28-539e4fa858a9)

**Comment by Elaine-Krauss-TCG** [comment]
There were 30 discrepancies in Schedule A
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/992911d0-f810-4b29-bb40-c12a778465e5)

Now also reduced to 0 errors
![image.png](https://images.zenhubusercontent.com/626ab5e81394ace64f8ed65d/0f398a47-11f9-4b1a-b453-1f5c83b31955)

**Comment by Elaine-Krauss-TCG** [comment]
@MitchellTCG 

These are the finished reports for Schedule A & B spec verification if they're at all useful.

[Schedule A Spec Verification Report](https://app.zenhub.com/files/184271254/75b615f5-b555-4287-a727-3fb76b688516/download)
[Schedule B Spec Verification Report](https://app.zenhub.com/files/184271254/c73fa039-b80b-4c63-9ab5-30cbc6ecee47/download)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
@AureliaKhorsand the Epic should also be Schedule A as these changes affect Schedule A also, since you like keeping track of Epics.  Schedule A had error as denoted during DEV testing.

QA Review Completed as an inspection per DEV team.   Moved to Stage Ready.
