### ISSUE TITLE
Remove sample tests code

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fecfile-Validate#21]
https://github.com/fecgov/fecfile-Validate/blob/3bb9d0315ce33241b3e1301f79053a2ea4c48cf4/api/tests.py

These tests aren't run by `pytest` and don't actually test anything, so we can probably remove them.

**Acceptance Criteria**
- [ ] The fecfile-validate:/api/tests.py file is removed from the repo

**Comment by lbeaufort** [comment]
Wrapping into https://github.com/fecgov/fecfile-Validate/pull/17 per @mjtravers

**Comment by mjtravers** [comment]
Issue handles in #17. Closing.
