### ISSUE TITLE
Add Schedule C1 to Data Dictionary

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#225]
In order to get the validation working with the back and front ends, a JSON validation spec needs to be created and linked into the online data dictionary as a baseline spec for the Schedule C1 transaction type definition specifications.

You can find the Schedule C1 specification from the Vendor pack: [HERE](https://docs.google.com/spreadsheets/d/18TtYCHWjj0gbsubJXQTbALEkbK_t93t0/edit#gid=373061151)

**Tasks:**

- Create a JSON validation file for the Schedule C1
- Put the JSON validation file created for Schedule C1 and put it in the schema directory of the GitHub repo along with the other schema JSON files
- Name the Schedule C1 JSON file in the schema directory in the GitHub repository "SchC1.json"
- Create the online documentation in the repository docs directory by running the bin/generate-schema-docs.sh script
- Update the docs/index.html page to include the new Schedule C1 schema in the [Forms & Schedules](https://fecgov.github.io/fecfile-validate/) section of the index.html page
- 
**QA Notes**
Passes if new schema code passes automated tests

**Comment by dheitzer** [comment]
reached out to the team to discuss the (form section?) prefixes in the SchC1 schemas (B.1. CREDIT AMOUNT THIS DRAW,  E.6 STREET  1, etc):

![image.png](https://images.zenhubusercontent.com/6298ce840c1c301e7c4a4151/c8a0b4e7-752d-43eb-bdab-61de3cbee935)

Proposed adding this to our validator in the following pattern:

"**authorized_last_name**": {
            "title": "**H. AUTHORIZED LAST NAME**",
            .
            .
            "fec_spec": {
                "COL_SEQ": 42,
                "FIELD_DESCRIPTION": "**H. AUTHORIZED LAST NAME**",
               .
               .
            }
        },

This way, our validator HTML documentation will refer to the schema names but we won't use these in our validator.

Will wait for any other suggestions.

**Comment by mjtravers** [comment]
Per CR, a few property name change suggestions and a correction in the HTML spec file are requested. Sending back to In Progress.

**Comment by mjtravers** [comment]
Changes made and pass CR. Sending to QA.

**Comment by mjtravers** [comment]
Here is a link showing code passes automated tests: https://app.circleci.com/pipelines/github/fecgov/fecfile-validate/943/workflows/327d7255-f040-4c6d-ba7d-51b360029e29/jobs/1874

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in Github per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/2b392ee3-8887-43cf-9c9e-33c3711f16a3)

QA Review Completed.  Moved to Stage Ready,
