### ISSUE TITLE
Add Schedule C2 to Data Dictionary

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#226]
In order to get the validation working with the back and front ends, a JSON validation spec needs to be created and linked into the online data dictionary as a baseline spec for the Schedule C2 transaction type definition specifications.

You can find the Schedule C2 specification from the Vendor pack: [HERE](https://docs.google.com/spreadsheets/d/18TtYCHWjj0gbsubJXQTbALEkbK_t93t0/edit#gid=560243710)

**Tasks:**

- Create a JSON validation file for the Schedule C2
- Put the JSON validation file created for Schedule C2 and put it in the schema directory of the GitHub repo along with the other schema JSON files
- Name the Schedule C2 JSON file in the schema directory in the GitHub repository "SchC2.json"
- Create the online documentation in the repository docs directory by running the bin/generate-schema-docs.sh script
- Update the docs/index.html page to include the new Schedule C2 schema in the [Forms & Schedules](https://fecgov.github.io/fecfile-validate/) section of the index.html page

**Comment by mjtravers** [comment]
For QA: Here is the link to the passing unit tests for the new C2 data dictionary: https://app.circleci.com/pipelines/github/fecgov/fecfile-validate/946/workflows/bea51383-37b6-4854-b003-575ba99001f5/jobs/1881

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of code passing as denoted in app.circleci per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/656989d6-0c23-4270-b71c-e65a7f9879f9)

QA Review Completed. Moved to Stage Ready,
