### ISSUE TITLE
Add Schedule D to Data Dictionary

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#227]
In order to get the validation working with the back and front ends, a JSON validation spec needs to be created and linked into the online data dictionary as a baseline spec for the Schedule D transaction type definition specifications.

You can find the Schedule D specification from the Vendor pack: [HERE](https://docs.google.com/spreadsheets/d/18TtYCHWjj0gbsubJXQTbALEkbK_t93t0/edit#gid=1060390329)

**Tasks:**

- Create a JSON validation file for the Schedule D
- Put the JSON validation file created for Schedule D and put it in the schema directory of the GitHub repo along with the other schema JSON files
- Name the Schedule D JSON file in the schema directory in the GitHub repository "SchD.json"
- Create the online documentation in the repository docs directory by running the bin/generate-schema-docs.sh script
- Update the docs/index.html page to include the new Schedule D schema in the [Forms & Schedules](https://fecgov.github.io/fecfile-validate/) section of the index.html page

**Comment by mjtravers** [comment]
QA NOTES: To verify schedule D is in the data dictionary, the Schedule D entry can be found here:

https://fecgov.github.io/fecfile-validate/

The details of the Schedule D in the data dictionary can be found here:

https://fecgov.github.io/fecfile-validate/SchD_spec.html

**Comment by WiseQA** [comment]
QA review verified Schedule D added to Data Dictionary per visual with DEV links (see links in QA Notes).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/c8db8204-5620-4fdd-95f0-5a4818d1ca47)

QA Review Completed. Move to Stage Ready after Sprint 26 review 22 June 2023.
