### ISSUE TITLE
Add Schedule E to Data Dictionary

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#250]
In order to get the validation working with the back and front ends, a JSON validation spec needs to be created and linked into the online data dictionary as a baseline spec for the Schedule E transaction type definition specifications.

You can find the Schedule E specification from the Vendor pack: [HERE](https://docs.google.com/spreadsheets/d/18TtYCHWjj0gbsubJXQTbALEkbK_t93t0/edit#gid=1726907415)

**Tasks:**

- Create a JSON validation file for the Schedule E
- Put the JSON validation file created for Schedule E and put it in the schema directory of the GitHub repo along with the other schema JSON files
- Name the Schedule E JSON file in the schema directory in the GitHub repository "SchE.json"
- Create the online documentation in the repository docs directory by running the bin/generate-schema-docs.sh script
- Update the docs/index.html page to include the new Schedule E schema in the [Forms & Schedules](https://fecgov.github.io/fecfile-validate/) section of the index.html page

**Comment by mjtravers** [comment]
Passes CR. Ready for QA.

QA Note: A spot check can be done using the online data dictionary entry for this spec: https://fecgov.github.io/fecfile-validate/SchE_spec.html

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of data dictionary entry per SchE_spec.html file per DEV.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a9c545f6-0f7c-4304-8165-2357dce13ef3)

QA Review Completed. Moved to Stage Ready,
