### ISSUE TITLE
Set minLength property to 1 for required fields

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#259]
For the schema validation properties that have the minLength set to 0, this should be updated to minLength: 1 for properties that are required. Although we do check for required by not allowing the "type" parameter to be "null", having a minLength set to 1 provides an additional validation check to ensure data integrity.

Current required example with minLength: 0

"payee_organization_name": {
            "title": "PAYEE ORGANIZATION NAME",
            "description": "",
            "type": "string",
            **"minLength": 0,**
            "maxLength": 200,
            "pattern": "^[ -~]{0,200}$",
            "examples": [
                "John Smith & Co."
            ],
            "fec_spec": {
                "FIELD_DESCRIPTION": "PAYEE ORGANIZATION NAME",
                "TYPE": "A/N-200",
                "REQUIRED": "X (error)",
                "SAMPLE_DATA": "John Smith & Co.",
                "RULE_REFERENCE": "Auto-generated from associated Schedule A IN_KIND receipt"
            }
        },

Example change to minLength to add additional validation check:

"payee_organization_name": {
            "title": "PAYEE ORGANIZATION NAME",
            "description": "",
            "type": "string",
            **"minLength": 1,**
            "maxLength": 200,
            "pattern": "^[ -~]{0,200}$",
            "examples": [
                "John Smith & Co."
            ],
            "fec_spec": {
                "FIELD_DESCRIPTION": "PAYEE ORGANIZATION NAME",
                "TYPE": "A/N-200",
                "REQUIRED": "X (error)",
                "SAMPLE_DATA": "John Smith & Co.",
                "RULE_REFERENCE": "Auto-generated from associated Schedule A IN_KIND receipt"
            }
        },

**QA Notes**
- To pass testing, the automated validator unit tests must pass.
- Expectation is front-end functionality should not change.

**DEV Notes**
- Please include list of fields impacted for QA.

**Comment by mjtravers** [comment]
During CR, some requested changes written up into the PR. Sending back to In Progress.

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
Automated test reports:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/4621/workflows/1fb21120-4814-47a5-bc9d-a1fd4240cb22/jobs/16486
<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3701c8fdd78eb74a30c9b2c0c1c0462509a47d0c/image.png" alt="image.png" />

https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/2844/workflows/5af4f513-6759-4b1a-b39e-5b825ffa0375/jobs/8973
<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWFoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--060053b8345037a69921819e6ef8eed956d1ae83/image.png" alt="image.png" />

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of Unit Test passing as denoted in app.circleci per DEV.

<img width="1214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bde6b9f74952713456f3c434d009fda9592890e6/image.png" alt="image.png" />

QA Review Completed. Moved to Stage Ready.
