### ISSUE TITLE
Add Form 1M to the Data Dictionary

### ISSUE THREAD

**Issue by GreggMoreland** [fecgov/fecfile-validate#261]
In order to get the validation working with the back and front ends, a JSON validation spec needs to be created and linked into the online data dictionary as a baseline spec for the Form 1M transaction type definition specifications.

You can find the Form 1M specification: [HERE](https://docs.google.com/spreadsheets/d/1ljw-_FReXCtMS88zRJDG94YsU7Pz5mxm-pI6ty_NUw0/edit#gid=1172431622)

**Tasks:**

- Create a JSON validation file for the Form 1M
- Put the JSON validation file created for Form 1M and put it in the schema directory of the GitHub repo along with the other schema JSON files
- Name the Form 1M JSON file in the schema directory in the GitHub repository "F1M.json"
- Create the online documentation in the repository docs directory by running the bin/generate-schema-docs.sh script
- Update the docs/index.html page to include the new Form 1M schema in the [Forms & Schedules](https://fecgov.github.io/fecfile-validate/) section of the index.html page

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**QA Notes:**

Automated tests here: https://app.circleci.com/pipelines/github/fecgov/fecfile-validate/1133/workflows/c43c2dac-3e2a-42ed-b92c-1e00e8fccdd4/jobs/2245

Data Dictionary here: https://fecgov.github.io/fecfile-validate/F1M_spec.html

**Comment by WiseQA** [comment]
QA review consisted of visual inspection of data dictionary entry per F1M_spec.html file per DEV.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac7fe703da8b30e6c56cd4e4e29d0c01782ad5c4/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenlpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4be5451d8cd3a6023a64609ddbc87e9089d892bd/image.png)

QA Review Completed. Moved to Stage Ready,
