### ISSUE TITLE
Validator JSON Verification Pass

### ISSUE THREAD

**Issue by Elaine-Krauss-TCG** [fecgov/fecfile-validate#291]
### Acceptance Criteria

Running the Spec Verification script with each of the five schedule spec sheets should produce zero errors.

### Dev Tasks

Download each of the five Spec Sheets as .xlsx files and run the diff checker script against them.  The script can be run with the command `python spec_verification [.xlsx file]` as run in the root of the Validate repo.  Each run of the script should produce zero errors.  This will likely require making changes to both the JSON schema files and, with the help of the BA's, the spec sheets themselves.  Screenshots should be taken of the results of the final runs showing zero errors.

The script is currently crashing because of the addition of the "COL SEQ" column to all of the spec sheets.  Fixing this should not be a large lift, but we can't run the script until it's dealt with.

 - [x] [Schedule A](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1335034634)
 - [x] [Schedule B](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1961093545)
 - [x] [Schedule C](https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=388194567) (Never before tested)
 - [x] C1
 - [x] C2
 - [x] [Schedule D](https://docs.google.com/spreadsheets/d/1ykulNJdRI6J_PwVWk80QzBaopHZKVaEkgEjDo7RHeKQ/edit#gid=1956508297) (Never before tested)
 - [x] [Schedule E](https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=1786117945) (Never before tested)
 
Additionally, with each spec sheet file, there may be sheets that can't be matched to a JSON schema file.  This is expected for sheets that haven't been implemented yet, but these warnings should be investigated to make sure that there isn't a mismatch in naming.  The Spec Verification script looks for a JSON schema file with a filename that matches Cell A2 on each sheet, such as in the example below:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUNEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--deb5ff2ae29d1be730ab64afb2264fec5f1cb54d/image.png)

### QA Notes

The dev should provide five screenshots showing the script having been run with zero errors in each.  Also, with changes to the JSON schema files, the behavior of individual transaction fields might be changed, depending on the errors being fixed in this ticket. If the dev working this ticket changes the minimum/maximum length, requirement, regex pattern, etc. of a field, they should note the transaction, field, and change in a comment.

**Comment by Elaine-Krauss-TCG** [comment]
You can download the Spec Sheets as .xlsx files from Google Sheets like so:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcc8d35b87b59c13379c45e9505cffe567007f8d/image.png)

**Comment by Elaine-Krauss-TCG** [comment]
## JSON Schemas changed [WIP]:

### Schedule A
- CONDUIT_EARMARKS
  - Reduced maximum length of `contribution_purpose_description` from 102 to 100 characters
  - Ensured that `memo_code` was required to be checked on an Undeposited Conduit Earmark

- LOAN_REPAYMENTS_RECEIVED
  - Ensured that `back_reference_trans_id` and `back_reference_sched_name` fields were required

### Schedule B

- CONDUIT_EARMARKS_OUT
  - Removed `memo_code` from the list of always-required fields
  - Updated the regex pattern for `beneficiary_candidate_fec_id` to match other schemas

- CANDIDATE_CONTRIBUTIONS
  - Updated the regex pattern for `beneficiary_candidate_fec_id` to match other schemas

**Comment by Elaine-Krauss-TCG** [comment]
Thanks in large part to @GreggMoreland 's cooperation, we now have zero discrepancies between the spec sheets and the JSON schema files.

![Image](https://github.com/fecgov/fecfile-validate/assets/104506225/9f440602-81d7-4315-b7c6-b5e4d5f955a0)

**Comment by Elaine-Krauss-TCG** [comment]
For comparison, see a screenshot of the script's output from earlier today after most, but not all, errors were squashed.

![Image](https://github.com/fecgov/fecfile-validate/assets/104506225/a8f8d50c-7dc6-49c4-8fb8-0db1de707219)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review visual inspection from DEV script's output. 

![Image](https://github.com/fecgov/fecfile-validate/assets/96139912/10fe1965-558a-4004-9b42-e5cf66135393)

QA Review Completed.   Moved to Stage Ready.
