### ISSUE TITLE
Perform code linting of fecfile-Validate in CircleCI

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-Validate#3]
Acceptance criteria:
* On commit, CircleCI should run flake8 against all the Python code in the repo
* Create a .flake8 configuration file
* The linting does NOT need to pass in CircleCI (i.e. we don't have to fix any the linting errors as part of this issue)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.
QA tests per acceptance criteria:
- Here is the successful run of linting in the validator repo: [See 'Run lint' step on this page](https://app.circleci.com/pipelines/github/fecgov/fecfile-Validate/23/workflows/264e2f9d-3f76-4430-b4c3-5f471e89b3b9/jobs/39)

**Comment by WiseQA** [comment]
Verified unit test passed successfully see below:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a2bd65d5-a67f-4539-a5c0-c1b0f2bdd3e8)

QA review completed.  Moved to Stage Ready.
