### ISSUE TITLE
Expand Validator Diff Checker Script to Cover Reports

### ISSUE THREAD

**Issue by Elaine-Krauss-TCG** [fecgov/fecfile-validate#303]
### Acceptance Criteria

The diff checker script should be able to be run on .xlsx files for report forms, and the script should check for errors in their corresponding JSON schema files.  Forms 1M, 24, and 99 should be supported, and running the script on each of them should produce zero errors.

### Dev Notes

Checking the Form spec sheets with the script will likely require changes to both the diff checker script and, with the BA's help, the spec sheets themselves.

- [x] [Form 1M](https://docs.google.com/spreadsheets/d/1ljw-_FReXCtMS88zRJDG94YsU7Pz5mxm-pI6ty_NUw0/edit#gid=1172431622)
- [x] [Form 24](https://docs.google.com/spreadsheets/d/1V-iOx4l6OzLrfIYRyK_iTzQz3Q1BCYj0/edit#gid=715507782)
- [x] [Form 99](https://docs.google.com/spreadsheets/d/1O2HKF5ND3YV0TYq87G0g4hKeX-VogoFXLLjORYElyQ4/edit#gid=1789273618)

### QA Notes

The dev should post screenshots showing that the script has been run on each of the three form spec sheets, producing zero errors in each.

**Comment by Elaine-Krauss-TCG** [comment]
![Image](https://github.com/fecgov/fecfile-validate/assets/104506225/7b4673aa-ef0c-4d64-97e3-2443afdec71c)

All that remains are three very minor discrepancies that I am inclined to believe should be corrected on the excel spec sheets.  It should only take the BA's a couple minutes.

**Comment by Elaine-Krauss-TCG** [comment]
No errors remain

![Image](https://github.com/fecgov/fecfile-validate/assets/104506225/9c4d0871-e487-40d9-b06e-2a394725055c)

**Comment by mjtravers** [comment]
Passes CR. Sending to QA.

**Comment by WiseQA** [comment]
QA review visual inspection from DEV script's output.

QA Review Completed.   Moved to Stage Ready.
