### ISSUE TITLE
Create validation schema files for contacts

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#33]
Create validation schema files for the 4 types of contacts using this [spec spreadsheet](https://docs.google.com/spreadsheets/d/181bZMw59iT3JdVOCOsjps5DIf8P2_gfa)

Use schema generation [script](https://github.com/fecgov/fecfile-validate/blob/develop/bin/generate-starter-schema.py)

Schema filenames as follows:
- Contact_Individual.json
- Contact_Committee.json
- Contact_Organization.json
- Contact_Candidate.json

**Acceptance Criteria**
- [x] schema file for Individual [QA see here](https://github.com/fecgov/fecfile-validate/blob/develop/schema/Contact_Individual.json)
- [x] schema file for Committee [QA see here](https://github.com/fecgov/fecfile-validate/blob/develop/schema/Contact_Committee.json)
- [x] schema file for Organization [QA see here](https://github.com/fecgov/fecfile-validate/blob/develop/schema/Contact_Organization.json)
- [x] schema file for Candidate [QA see here](https://github.com/fecgov/fecfile-validate/blob/develop/schema/Contact_Candidate.json)
- [x] list and show 4 new schema in [GitPages](https://fecgov.github.io/fecfile-validate/)

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/9/22:** Pointed at 3.
