### ISSUE TITLE
Run unit tests for fecfile-Validate in CircleCI

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-Validate#4]
Acceptance Criteria:
* On commit, unit tests for this repo should be run in Circle CI
* At least 1 unit test must be present and passing
* Skip out any failing tests so that we get a clean result from CI for unit tests

**Comment by albertcrowley** [comment]
For QA: You can see the result of the unit tests in our CI pipeline here: https://app.circleci.com/pipelines/github/fecgov/fecfile-Validate/15/workflows/4725a231-c5f8-4224-b050-f5ad345bbb75/jobs/23

**Comment by WiseQA** [comment]
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/0e7d2244-1793-4f7c-978f-9036ca763289)
