### ISSUE TITLE
Create initial validation schema for OP1 transactions

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#44]
As part of OP1, there are 64 transaction types that are listed [here](https://docs.google.com/spreadsheets/d/1gdcvYQBFMeCGt-1NfVuaSTsB0sB-dl2N/edit#gid=1395788914). See which transaction types have been defined [here](https://docs.google.com/spreadsheets/d/1jZLQWVvXgzpST4bP7tn3SlovUf4pC16e/edit#gid=1384755145) and generate the validation schema files for them. Note which of the 64 transaction types do not have schema definitions.

**Acceptance Criteria**
1. Display new transaction types in [online documentation](https://fecgov.github.io/fecfile-validate/) **QA**: The new transaction types are the forms starting at BUS_LAB_NON_CONT_ACC and below.
2. Update [spreadsheet](https://docs.google.com/spreadsheets/d/1gdcvYQBFMeCGt-1NfVuaSTsB0sB-dl2N/edit#gid=1395788914) showing which transaction types are still missing definitions. **QA**: Look at column I in the "TXN Groups" tab of the spreadsheet.
3. This ticket does not make any changes to the UI. All verification is done using the 2 links in 1 and 2 of the acceptance criteria

**Comment by AureliaKhorsand** [comment]
**Refinement Meeting 2/23/22:** This ticket is to merge this code into the develop branch. This has been done due to roadmap work.

**Comment by WiseQA** [comment]
Verified new transaction types are the forms starting at BUS_LAB_NON_CONT_ACC and below.
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/66b9de98-a664-45e9-9f08-6cde214274de)

Verified from spreadsheet denoted in Acceptance Criteria "Column H" highlighted in red identifies missing transactions to be verified with FEC what is missing.   (Note:  Changed acceptance criteria from Column I to Column H in step 2.)

QA review completed.  Moved to Stage Ready.
