### ISSUE TITLE
Integrate JSON schema standard into current validation JSON files

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#5]
Currently, the validator code captures rules in JSON formatted files.

https://github.com/fecgov/fecfile-Validate/tree/master/api/rules

Upgrade or replace these files so that they conform to the JSON schema standard. Using the schema standard will allow the development team to leverage open source libraries that are built on the standard to process and manipulate FEC data.

http://json-schema.org/

The baseline rules can be found in the VendorPack download that is used to distribute the FECFile desktop application.

https://efilingapps.fec.gov/registration/fecfile.htm

HTML pages can be generated to share the validation rules via GitPages using third party software such as the python library json-schema-for-humans

Collections of fields that are common across forms and schedules will be pulled into separate data definition files that can be shared across form and schedule data definition files.

**Acceptance Criteria:**

- [x] Schema data definition files for Form 3X and Schedule A shared in the repository.
- [x] Unit tests validating Form 3X and Schedule A test data against data definition files.
- [x] Basic HTML pages built showing validation rules and served by GitPages in repo /docs directory

**Comment by lbeaufort** [comment]
Github pages now set up on the `develop` branch and `/docs` directory:
<img width="1183" alt="Screen Shot 2022-01-10 at 9 16 42 AM" src="https://user-images.githubusercontent.com/31420082/148780675-201ac054-6e17-4e96-8261-5f3b0a49348c.png">

**Comment by mjtravers** [comment]
Passes CR and ready for QA. For QA, there are some HTML pages that display the new schema data definition files in human-readable form. The URL to view and confirm the acceptance criteria is: https://fecgov.github.io/fecfile-validate/

**Comment by WiseQA** [comment]
@mjtravers @toddlees where is the Unit Test from the acceptance criteria ?  "Unit tests validating Form 3X and Schedule A test data against data definition files."   I can validate the  FEC Form Data Dictionaries.

**Comment by mjtravers** [comment]
@WiseQA Here is a link to the CircleCI unit-test report for the new validator code showing the unit tests passing: https://app.circleci.com/pipelines/github/fecgov/fecfile-validate/66/workflows/6c8f9b2a-1708-4788-a6d7-0467bd5a4d82/jobs/142

**Comment by WiseQA** [comment]
Few things caught during QA / Test Review.   After talking with Matt returned to "In-progress" to fix:
1.  Change Form names in data dictionary from acronyms to full name (e.g., SA > Schedule A)
2.  Notation on "Schema" pages for all forms where fields are located (e.g., Form 3x pages 1 through 5).
3.  Required fields in Schema only showing "Errored" fields, adding "Warning" fields to schema.  

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/9a2c51eb-2a0d-4f11-8b29-f05e396b1c05)

Matt please add any additional items I may have missed.

**Comment by mjtravers** [comment]
Ready for QA:

Items #1 and #2 from QA were addressed in the data dictionary home page table. The **Form** column now contains the full name of the form and the new **Description** column holds notation about the form such as "pages 1 through 5"

Item #3 was captured in the JSON document as a new property called "recommended" that is intentionally differentiated from the "required" property. This was done because the "warning" fields will still allow the user to submit the form if they are missing which does not really meet the definition of required. The "recommended" field was added to the schema and can be verified to be an array at the top of the F3X and SchA schema files directly:

- https://github.com/fecgov/fecfile-validate/blob/develop/schema/F3X.json#L15:L27
- https://github.com/fecgov/fecfile-validate/blob/develop/schema/SchA.json#L17:L24

NOTE: The incorporation of the non-standard "recommended" attribute means the off-the-shelf software creating the HTML documents will not display the field. Modifying the software to have do so is out of the scope of this ticket and will be added to a future ticket.

**Comment by WiseQA** [comment]
Verified changes were made:
1.  Change Form names in data dictionary from acronyms to full name (e.g., SA > Schedule A)
2.  Notation on "Schema" pages for all forms where fields are located (e.g., Form 3x pages 1 through 5).
3.  Required fields in Schema only showing "Errored" fields, adding "Warning" fields to schema from "required field" in SPEC.

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/54a59e23-2546-4d56-bfd8-ea42d5d10af5)

Verified Unit Test:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/e056d361-d7e3-446d-836c-6603bead643b)

QA review completed.  Moved to Stage Ready.
