### ISSUE TITLE
Create a JSON Schema file for committee accounts

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#51]
There is no spreadsheet to convert into a JSON file for this so the task is to piece together a JSON schema file by:

- Examining the committee_master table in the database
- Look at the spec for the Form 1 to get validation rules and field types
- Create a temporary spec spreadsheet in google docs and have it reviewed for comments by Ryan

**Acceptance Criteria**
- JSON schema file for committee_accounts
- Generated data dictionary document for committee_accounts
- HTML spec page for committee_accounts
- New entry on the /doc index.html page for committee_accounts

**Comment by AureliaKhorsand** [comment]
Duplicate/overtaken by [web-app #87](https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/87).
