### ISSUE TITLE
Fix code lint issues in fecfile-Validate

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-Validate#6]
Acceptance Criteria:
* Run any automated code fixes available
* Where possible, for error categories that have 3 or fewer instances use the "# noqa" marker to skip those particular violations. See [Ignoring Errors with Flake8](https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html)
* Modify the flake8 configuration file to skip any linting issues that can't be fixed without semantic code changes and have 4 or more violations

**Comment by albertcrowley** [comment]
Due to comments/resolution made code review, this is going to be fixed as part of Issue #3 
I will add QA notes when #3 moves into QA.

**Comment by WiseQA** [comment]
Verified acceptance criteria and no testing required.  This ticket is not being done, as this fix as noted above will be completed in Issue #3.  QA review completed.  Moved to Stage Ready.
