### ISSUE TITLE
Implement javascript/typescript code coverage for SonarCloud

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#60]
Currently, SonarCloud can only report on code coverage for the python code in the fecfile-validate repo. We need the CircleCI configuration to also pass code coverage information to SonarCloud for the fecfile_validate_js code.

Since we do not have this set up, SonarCloud is reporting 0% code  coverage for fecfile_validate_js code which is not correct.

## Business Reason ##
The testing code coverage report for all our apps must be accurate so that we can meet QASP requirements.

## Technical Notes ##
- Update sonar-project.properties file to scan for javascript and typescript files
- Running tests is done with this command: npm test
- Create a code coverage report in CircleCI to feed to SonarCloud. [Docs on generating a coverage report are here](https://deno.land/manual@v1.12.2/testing/coverage)

## Acceptance Criteria ##
**If** I am a FEC staff member
**When** I am looking at code coverage reports generated by SonarCloud
**Then** I will see accurate percentage numbers of the number of lines of python and javascript code that are covered by unit tests

## QA ##
The process set up is to run the code coverage for javascript and report the coverage percentage to SonarCloud. Visual inspection of the [CircleCI output under "Run deno tests, save a coverage report, and save coverage percentage"](https://app.circleci.com/pipelines/github/fecgov/fecfile-validate/307/workflows/fbfe872e-f6d5-46e6-96cf-8fde540a174e/jobs/629) show that the code coverage percentage is calculated currently to be 94.5%

**Comment by mjtravers** [comment]
Passes code review. Code coverage percentage for javascript is now showing up in the CircleCI logging. Sending to QA

**Comment by WiseQA** [comment]
QA verified percentage for "Run deno tests, save a coverage report, and save coverage percentage" see below screenshot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/786645de-c2b1-40fe-aad1-136644727e3d)

QA review completed.  Moved to Stage Ready.
