### ISSUE TITLE
Allow special characters in text fields

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-validate#61]
**Special Characters FECFile Online should accept:**

- ASCII 32 – 126 
`space, !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{|}~` _and_ `

[See eFiling Specification PDF here](https://drive.google.com/file/d/180k57BGj2P-X2DMhQcXhSo3F_QB_B9Nf/view?usp=sharing). Accepted characters on page 3. Sample ASCII table [here](https://www.rapidtables.com/code/text/ascii-table.html).

### QA Notes:

To verify this on a screen, go to **Add Contact** page and try typing any _allowed_ special characters (from above) into **LAST NAME** field.  There should be _no_ error text listed below.  

Next, try adding a disallowed special character (tab) in **LAST NAME** by clicking the field and typing Ctrl + Shift + U, then 09, then space.  This sequence will add a tab character to the field that should then read "**This field contains characters that are not allowed**."

### end QA Notes

**Comment by AureliaKhorsand** [comment]
This ticket is moving back to ADTR since it has increased in scope to include all text fields across FECFile online. Need to confer with Dev/QA on how to write ACs.

**Comment by AureliaKhorsand** [comment]
**5/11/22 Refinement meeting notes:** Assumption is that this will be the default for each text field, unless there is a specific value/rule reference in the spec. This will be a unit test in the validate repo. Devs will add a sampling list of fields for QA to verify when they develop the ticket.

**Comment by WiseQA** [comment]
QA reviewed this ticket and verified special characters (e.g., @#$^*&^) "This field cannot contain more than 30 alphanumeric characters." for both "Required" and "Optional" fields.  Verified all contacts (e.g., Individual, Committee, Organization and Committee).

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/8bef8202-4e66-48e9-84fb-6463ddee2cd3)

NOTE:  e2e testing for all special characters will need to be implemented for all special characters denoted in Acceptance Criteria .pdf attached file.

QA review completed.  Moved to Stage Ready.
