### ISSUE TITLE
Add test coverage report to CI Pipeline for fecfile-Validate

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-Validate#7]
Acceptance Criteria:
* On each commit, generate a test coverage report 
* Code coverage report should include a total percent coverage summary number

**Comment by albertcrowley** [comment]
For QA: You can see results of CI pipeline for this fix here: https://app.circleci.com/pipelines/github/fecgov/fecfile-Validate/16/workflows/ebf8b1d0-bf13-41b0-8ada-751d0751af26/jobs/24/artifacts

the coverage report should be visible here (if there isn't any issue with the CircleCI DNS changing) : https://24-184271254-gh.circle-artifacts.com/0/htmlcov/index.html

**Comment by WiseQA** [comment]
Unit test results verified see below:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/a46c954b-fc14-4a99-94a0-267086acce95)
