### ISSUE TITLE
Update schemas to use boolean and date data types

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-validate#75]
Convert the old spec "X" and "YYYYMMDD" fields in the F3X, SchA, and transaction type schemas to boolean and string, format: date-time, respectively. The updates to the new validation definitions are more robust and future-proof to changes in the specs going forward.

### Tech Notes ###

Fields to update in (1) validate schema, (2) Django model, and (3) Angular models
- F3X.change_of_address (boolean)
- F3X.date_of_election (date)
- F3X.coverage_from_date (date)
- F3X.coverage_through_date (date)
- F3X.qualified_committee (boolean)
- F3X.date_signed (date)
- SchA.contribution_date (date)
- SchA.memo_code (boolean)
- OFFSET_TO_OPEX.contribution_date (date)
- OFFSET_TO_OPEX.memo_code (boolean)

Here is the [info on the date-time format for JSON schema](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times)

IMPORTANT: Validate that the javascript JSON.parse() and Django equivalent JSON parser convert the date type into the JSON schema date-time format (i.e. 2018-11-13T20:20:39+00:00)

### Acceptance Criteria ### 

- Schema fields listed above in tech notes have been updated.
[F3X Schema](https://github.com/fecgov/fecfile-validate/blob/develop/schema/F3X.json)
[Sched A Schema](https://github.com/fecgov/fecfile-validate/blob/develop/schema/SchA.json)
[OFFSET_TO_OPEX schema](https://github.com/fecgov/fecfile-validate/blob/develop/schema/OFFSET_TO_OPEX.json)
- All unit tests and e2e tests pass

### QA Notes ###
[API unit tests](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/512/workflows/cc5d42b6-b7b9-4c78-84ea-4d90a674505e/jobs/1447/steps)
[App unit tests](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-app/681/workflows/11b45e8d-42bd-4291-bb6a-86e779757c8b/jobs/2481)
[Validate unit tests](https://app.circleci.com/pipelines/github/fecgov/fecfile-validate/316/workflows/25273510-0ec2-4f9b-a0ec-f17fc63902a3/jobs/647)

**Comment by mjtravers** [comment]
Technical note: Due to errors being thrown by the ajv validation library when loading the ajv-formats extension, the "format": "date" property has been replaced by "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$", which performs the same string check

**Comment by WiseQA** [comment]
QA verified API unit test passed successfully as denoted in the QA Notes see below screenshot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/36c2f751-dac7-41a4-b790-483cc7750308)

QA verified APP unit test passed successfully as denoted in the QA Notes see below screenshot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/518d1e3b-387e-418a-b855-3ecd8714693b)

QA verified Validate unit test passed successfully as denoted in the QA Notes see below screenshot:

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/99fd32d8-7cfe-43d0-950b-74685caf1822)

QA review completed.  Moved to Stage Ready.
