### ISSUE TITLE
Add security check for out of date Python packages in CI Pipeline to fecfile-Validate

### ISSUE THREAD

**Issue by albertcrowley** [fecgov/fecfile-Validate#8]
Acceptance Criteria:
* Use a tool such as [Safety](https://pypi.org/project/safety/) to check any Python dependencies on each commit

**Comment by albertcrowley** [comment]
Ready for QA Review.  
You can see the results of a failing dependency check here:
https://app.circleci.com/pipelines/github/fecgov/fecfile-Validate/26/workflows/13e647b3-42df-4f07-b09a-8507dd2da133/jobs/45

The current version of the build is passing the dependency check (after marking the gunicorn package for update later this month) as seen here:
https://app.circleci.com/pipelines/github/fecgov/fecfile-Validate/27/workflows/4a60d779-02f6-4d40-9f44-56ea5c011572/jobs/48

**Comment by WiseQA** [comment]
Failing dependency for checking out of date Python packages verified in CI pipeline (see below):

![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/b78dcbcd-bfdd-4b03-b5c3-cbdf929be8f5)
